// Regression tests: the JS engine must reproduce the Python engine's numbers.
//
// Expectations are READ FROM engine.fixtures.json, which is generated by
// calculator/gen_test_fixtures.py from code/uk_horse_race_v2.py. They are
// deliberately not literals in this file: the previous version carried them as
// literals, and when the baseline was recalibrated (five-year fix repriced by
// loan-to-value, 1.2% purchase and 1.8% selling costs) the literals silently
// described a specification the engine no longer ran, so the suite passed
// against the wrong model.
//
// Run: python calculator/gen_test_fixtures.py
//      python calculator/build_calculator.py
//      node   calculator/engine.test.mjs
import { createRequire } from 'module';
import { readFileSync } from 'fs';
const require = createRequire(import.meta.url);
const E = require('./engine.js');

const FX = JSON.parse(readFileSync(new URL('./engine.fixtures.json', import.meta.url), 'utf-8'));
const dataSrc = readFileSync(new URL('./calculator_data.js', import.meta.url), 'utf-8');
const CALC_DATA = eval(dataSrc + '; CALC_DATA');

let failures = 0;
function check(name, got, want, tol = 0) {
  const ok = typeof want === 'number' ? Math.abs(got - want) <= tol : got === want;
  if (!ok) failures++;
  console.log(`${ok ? 'OK  ' : 'FAIL'} ${name}: got ${got}, want ${want}${tol ? ' ±' + tol : ''}`);
}

// The JS params mirror the Python BASE_SPEC recorded in the fixtures, so a
// change to the baseline shows up here as a failure rather than as a silent
// divergence between the two engines.
const B = FX.baseline;
const P = {
  depositShare: B.deposit_share,
  amortYears: B.amort_years,
  maintPct: B.maintenance_pct_of_value,
  purchaseCostsPct: B.purchase_costs_pct,
  sellingCostsPct: B.selling_costs_pct,
  includeSdlt: B.include_sdlt,
  fixationYears: B.rate_fixation_years,
  rentGrowthAnnual: FX.rent_growth_annual,
};
console.log(`baseline: ${B.deposit_share * 100}% deposit, ${B.amort_years}y term, ` +
            `${B.rate_fixation_years}y fix, ${B.maintenance_pct_of_value * 100}% maintenance, ` +
            `${B.purchase_costs_pct * 100}%/${B.selling_costs_pct * 100}% costs\n`);

// ---- 1. Stamp duty, every schedule change in the sample ----
for (const c of FX.sdlt) {
  const [y, m] = c.date.split('-').map(Number);
  check(`SDLT ${c.date.slice(0, 7)} £${c.price}`,
        E.sdltEnglandFTB(c.price, y, m), c.expected, 0.51);
}

// ---- 2. Rate repricing by loan-to-value ----
// Below 75% the 75% rate is used unchanged; the bands interpolate linearly.
check('rateForLtv at 0.60', E.rateForLtv(0.04, 0.05, 0.06, 0.60), 0.04, 1e-12);
check('rateForLtv at 0.75', E.rateForLtv(0.04, 0.05, 0.06, 0.75), 0.04, 1e-12);
check('rateForLtv at 0.90', E.rateForLtv(0.04, 0.05, 0.06, 0.90), 0.05, 1e-12);
check('rateForLtv at 0.95', E.rateForLtv(0.04, 0.05, 0.06, 0.95), 0.06, 1e-12);
check('rateForLtv midband 0.825', E.rateForLtv(0.04, 0.05, 0.06, 0.825), 0.045, 1e-12);
check('rateForLtv above 0.95', E.rateForLtv(0.04, 0.05, 0.06, 0.99), 0.06, 1e-12);

// ---- 3. Historical engine vs Python, representative series ----
const S = CALC_DATA.series['England (representative)'];
const data = {
  prices: S.prices, rents: S.rents, rates: CALC_DATA.rates,
  bands: CALC_DATA.bands, returns: CALC_DATA.returns, ym: CALC_DATA.ym,
};
check('months', data.prices.length, FX.months);
check('bands present', !!(data.bands && data.bands.r90), true);

const n = data.prices.length;
const single = E.runPair(data, 0, n, P);
check('single-start R', single.R, FX.single.R, 0.0002);
check('single NW buy', Math.round(single.buy.netWorth), FX.single.nw_buy, 5);
check('single NW rent', Math.round(single.rent.netWorth), FX.single.nw_rent, 5);
check('single SDLT', single.buy.sdlt, FX.single.sdlt, 2);
check('single purchase price', Math.round(single.buy.purchasePrice), FX.single.purchase_price, 1);

// ---- 4. The headline design: fixed five-year holds, monthly starts ----
const c5 = E.runRollingFixed(data, 60, P);
check('5y cohorts', c5.length, FX.cohorts_5y.n);
check('5y buy wins', c5.filter(c => c.winner === 'BUY').length, FX.cohorts_5y.buy_wins);
const median = a => { const s = [...a].sort((x, y) => x - y); const h = s.length >> 1;
  return s.length % 2 ? s[h] : (s[h - 1] + s[h]) / 2; };
check('5y median R', median(c5.map(c => c.R)), FX.cohorts_5y.R_median, 0.0001);
check('5y mean R', c5.reduce((a, c) => a + c.R, 0) / c5.length, FX.cohorts_5y.R_mean, 0.0001);
check('5y min R', Math.min(...c5.map(c => c.R)), FX.cohorts_5y.R_min, 0.0001);
check('5y max R', Math.max(...c5.map(c => c.R)), FX.cohorts_5y.R_max, 0.0001);
check('5y median gap', median(c5.map(c => c.nwRent - c.nwBuy)), FX.cohorts_5y.gap_median_gbp, 5);
check('5y min owner NW', Math.min(...c5.map(c => c.nwBuy)), FX.cohorts_5y.nw_buy_min_gbp, 5);

const c10 = E.runRollingFixed(data, 120, P);
check('10y cohorts', c10.length, FX.cohorts_10y.n);
check('10y buy wins', c10.filter(c => c.winner === 'BUY').length, FX.cohorts_10y.buy_wins);
check('10y median R', median(c10.map(c => c.R)), FX.cohorts_10y.R_median, 0.0001);

// ---- 5. Forward-looking required appreciation, end-of-sample conditions ----
const F = FX.forward;
const priceNow = data.prices[n - 1], rentNow = data.rents[n - 1];
check('price now', priceNow, Math.round(F.price_now), 1);
const [yN, mN] = data.ym[n - 1];
const sdltNow = E.sdltEnglandFTB(priceNow, yN, mN);
check('SDLT now', sdltNow, F.sdlt_now, 2);
for (const h of Object.keys(F.rar)) {
  const got = E.requiredAppreciationRate(priceNow, rentNow, F.rate_now,
                                         FX.equity_opportunity_annual, Number(h), P, sdltNow);
  check(`forward RAR ${h}y`, got, F.rar[h], 0.00001);
}

console.log(failures === 0 ? '\nALL ENGINE TESTS PASSED' : `\n${failures} FAILURES`);
process.exit(failures === 0 ? 0 : 1);
